name: secure_store
description: Zero-config wallet components for starknet
version: 0.1.3
homepage: https://github.com/gabsn/starknet.dart/tree/main/packages/secure_store

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.5.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  # versions contrainted by workspace
  pointycastle:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.secure_store
        pluginClass: SecureStorePlugin
      ios:
        pluginClass: SecureStorePlugin
      macos:
        pluginClass: SecureStorePlugin
