name: ark_project
description: Ark SDK for Dart and Flutter apps.
version: 0.4.0
repository: https://github.com/focustree/starknet.dart

environment:
  sdk: ">=3.6.0 <4.0.0" # Dart version constraint

resolution: workspace

dependencies:
  http: ^1.2.2
  starknet: ^0.2.0
  starknet_provider: ^0.2.0
  # versions contrainted by workspace
  freezed_annotation:
  json_annotation:

dev_dependencies:
  build_runner:
  dotenv: ^4.2.0
  freezed:
  json_serializable:
  test: ^1.25.8
